import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { NavLink,Navigate,Route,Routes,useLocation } from "react-router-dom";
import { Activity,ArrowDownLeft,ArrowUpRight,BookOpen,Boxes,Braces,Building2,Check,ChevronDown,CircleHelp,Command,Copy,CreditCard,Database,ExternalLink,FileClock,Gauge,KeyRound,Landmark,Menu,Plus,Search,ServerCog,Settings,ShieldCheck,WalletCards,X,Zap } from "lucide-react";
import { api,type CreatePayment,type LedgerEntry,type Payment,DEMO_MODE } from "./api";
import "./App.css";

const money=(n:number,c="GBP")=>new Intl.NumberFormat("en-GB",{style:"currency",currency:c}).format(n/100);
const date=(v:string)=>new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(v));
const short=(id:string)=>id.slice(0,8).toUpperCase();
const nav=[["/overview","Overview",Gauge],["/payments","Payments",CreditCard],["/accounts","Accounts",WalletCards],["/ledger","Ledger",BookOpen],["/developers","Developers",Braces]] as const;

export default function App(){
 const [mobile,setMobile]=useState(false);
 return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><i><Landmark/></i><div><strong>ClearLedger</strong><small>Payments infrastructure</small></div><button onClick={()=>setMobile(false)}><X/></button></div><div className="workspace"><span>Workspace</span><button><b>N</b><div><strong>Northstar Commerce</strong><small>Production</small></div><ChevronDown/></button></div><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} onClick={()=>setMobile(false)}><Icon/><span>{label}</span>{label==="Payments"&&<em>live</em>}</NavLink>)}</nav><div className="sidebar-spacer"/><div className="rail-status"><p><i/> Systems operational</p><span>API p95 <b>84 ms</b></span><span>Event lag <b>0</b></span></div><nav className="secondary"><a href="http://localhost:8080/docs"><CircleHelp/>API documentation<ExternalLink/></a><a href="#settings"><Settings/>Settings</a></nav><div className="user"><b>AM</b><div><strong>Alex Morgan</strong><small>Platform engineer</small></div></div></aside><main><Topbar onMenu={()=>setMobile(true)}/><Routes><Route path="/overview" element={<Overview/>}/><Route path="/payments" element={<Payments/>}/><Route path="/accounts" element={<Accounts/>}/><Route path="/ledger" element={<Ledger/>}/><Route path="/developers" element={<Developers/>}/><Route path="*" element={<Navigate to="/overview" replace/>}/></Routes></main></div>
}
function Topbar({onMenu}:{onMenu:()=>void}){const location=useLocation(),title=nav.find(([to])=>to===location.pathname)?.[1]??"Overview";return <header className="topbar"><button className="menu" onClick={onMenu}><Menu/></button><div><small>Northstar Commerce</small><strong>{title}</strong></div><label className="search"><Search/><input placeholder="Search payments, accounts, references…"/><kbd><Command/> K</kbd></label><button className="help"><CircleHelp/></button><span className="env"><i/> Live</span><button className="avatar">AM</button></header>}
function Page({eyebrow,title,copy,action,children}:{eyebrow:string;title:string;copy:string;action?:React.ReactNode;children:React.ReactNode}){return <div className="page"><header className="pagehead"><div><p>{eyebrow}</p><h1>{title}</h1><span>{copy}</span></div>{action}</header>{DEMO_MODE&&<div className="demo-banner"><Zap/> Demo adapter active. Set <code>VITE_DEMO_MODE=false</code> to use the Spring API.<button>Architecture <ArrowUpRight/></button></div>}{children}</div>}
function PanelTitle({eyebrow,title,action}:{eyebrow:string;title:string;action?:React.ReactNode}){return <header className="paneltitle"><div><p>{eyebrow}</p><h2>{title}</h2></div>{action}</header>}

function Overview(){
 const dashboard=useQuery({queryKey:["dashboard"],queryFn:()=>api.dashboard()}),payments=useQuery({queryKey:["payments"],queryFn:()=>api.payments()}),d=dashboard.data;
 return <Page eyebrow="Monday, 28 September · 18:57 UTC" title="Money movement, under control." copy="One operational view of balances, payments, and ledger integrity." action={<NavLink to="/payments" className="primary"><Plus/>Create payment</NavLink>}><section className="metrics"><Metric icon={Landmark} label="Platform balance" value={money(d?.totalBalanceMinor??246816900)} sub="Across 4 GBP accounts" change="+4.8%"/><Metric icon={ArrowUpRight} label="Processed volume" value={money(d?.processedVolumeMinor??128472900)} sub="Rolling 30 days" change="+12.4%"/><Metric icon={Check} label="Completed payments" value={(d?.completedPayments??1842).toLocaleString()} sub="99.94% success rate" change="+8.2%"/><Metric icon={FileClock} label="Pending outbox events" value={String(d?.pendingEvents??0)} sub="Kafka delivery backlog" change="Healthy"/></section><section className="overview-grid"><article className="panel volume"><PanelTitle eyebrow="Processing volume" title="£1.28m moved this month" action={<select><option>Last 14 days</option><option>Last 30 days</option></select>}/><div className="chart"><div className="axis"><span>£160k</span><span>£120k</span><span>£80k</span><span>£40k</span><span>£0</span></div><div className="columns">{[64,76,58,91,84,113,96,127,109,142,125,151,136,159].map((v,i)=><i key={i} style={{height:`${v/1.7}px`}} className={i>11?"hot":""}><b>{i===13?"£159k":""}</b></i>)}</div><div className="days"><span>15 Sep</span><span>18 Sep</span><span>21 Sep</span><span>24 Sep</span><span>28 Sep</span></div></div><footer><span><i/> Card payments</span><span><i/> Settlements</span><b>+12.4% vs previous period</b></footer></article><article className="panel integrity"><PanelTitle eyebrow="Ledger controls" title="Integrity monitor"/><div className="integrity-score"><i><ShieldCheck/><b>100%</b></i><div><strong>All controls passing</strong><span>Last verified 12 seconds ago</span></div></div><ul><li><Check/><span>Debits equal credits</span><b>Passing</b></li><li><Check/><span>No orphan postings</span><b>Passing</b></li><li><Check/><span>Sequence continuity</span><b>Passing</b></li><li><Check/><span>Outbox delivery</span><b>Passing</b></li></ul><button>View control evidence <ArrowUpRight/></button></article></section><RecentPayments items={payments.data??[]}/></Page>
}
function Metric({icon:Icon,label,value,sub,change}:{icon:typeof Landmark;label:string;value:string;sub:string;change:string}){return <article className="metric"><header><i><Icon/></i><span>{label}</span></header><strong>{value}</strong><footer><span>{sub}</span><b>{change}</b></footer></article>}
function RecentPayments({items}:{items:Payment[]}){
 const accounts=useQuery({queryKey:["accounts"],queryFn:()=>api.accounts()}).data??[],names=Object.fromEntries(accounts.map(a=>[a.id,a.name]));
 return <article className="panel tablepanel"><PanelTitle eyebrow="Live stream" title="Recent payments" action={<NavLink to="/payments">View all <ArrowUpRight/></NavLink>}/><div className="table"><div className="tr th"><span>Payment</span><span>Route</span><span>Amount</span><span>Status</span><span>Created</span></div>{items.slice(0,8).map(p=><div className="tr" key={p.id}><span><i className="payment-icon"><ArrowUpRight/></i><b>{p.merchantReference}<small>PAY_{short(p.id)}</small></b></span><span>{names[p.sourceAccountId]??"Operating wallet"}<small>→ {names[p.destinationAccountId]??"Merchant"}</small></span><strong>{money(p.amountMinor,p.currency)}</strong><em><Check/> {p.status.toLowerCase()}</em><time>{date(p.createdAt)}</time></div>)}</div></article>
}

function Payments(){
 const query=useQuery({queryKey:["payments"],queryFn:()=>api.payments()}),[open,setOpen]=useState(false);
 return <Page eyebrow="Payment orchestration" title="Payments" copy="Idempotent transfers posted atomically to the double-entry ledger." action={<button className="primary" onClick={()=>setOpen(true)}><Plus/>Create payment</button>}><section className="filterbar"><div><button className="active">All</button><button>Completed</button><button>Processing</button><button>Failed</button></div><label><Search/><input placeholder="Reference or payment ID"/></label><button><FileClock/>Export CSV</button></section><RecentPayments items={query.data??[]}/>{open&&<PaymentDialog close={()=>setOpen(false)}/>}</Page>
}
function PaymentDialog({close}:{close:()=>void}){
 const qc=useQueryClient(),accounts=useQuery({queryKey:["accounts"],queryFn:()=>api.accounts()}).data??[];
 const [source,setSource]=useState("11111111-1111-1111-1111-111111111111"),[destination,setDestination]=useState("33333333-3333-3333-3333-333333333333"),[amount,setAmount]=useState("1250.00"),[reference,setReference]=useState(()=>`ORD-${Date.now().toString().slice(-5)}`);
 const mutation=useMutation({mutationFn:(input:CreatePayment)=>api.createPayment(input),onSuccess:async()=>{await qc.invalidateQueries({queryKey:["payments"]});await qc.invalidateQueries({queryKey:["dashboard"]});close()}});
 const submit=(e:React.FormEvent)=>{e.preventDefault();mutation.mutate({merchantReference:reference,sourceAccountId:source,destinationAccountId:destination,amountMinor:Math.round(Number(amount)*100),currency:"GBP",description:"Merchant order settlement"})};
 return <div className="modal" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="dialog" onSubmit={submit}><header><div><p>New transfer</p><h2>Create payment</h2><span>Funds and ledger postings commit in one transaction.</span></div><button type="button" onClick={close}><X/></button></header><label>Merchant reference<input value={reference} onChange={e=>setReference(e.target.value)} required/></label><div className="twocol"><label>Source account<select value={source} onChange={e=>setSource(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {money(a.balanceMinor)}</option>)}</select></label><label>Destination account<select value={destination} onChange={e=>setDestination(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><label>Amount<div className="amount"><span>GBP</span><input type="number" min=".01" step=".01" value={amount} onChange={e=>setAmount(e.target.value)}/></div></label><aside><ShieldCheck/><span><strong>Protected by ledger controls</strong>Idempotency, row locks, balanced postings and an outbox event.</span></aside>{mutation.error&&<p className="error">{mutation.error.message}</p>}<footer><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={mutation.isPending}>{mutation.isPending?"Posting…":"Create payment"}<ArrowUpRight/></button></footer></form></div>
}

function Accounts(){
 const query=useQuery({queryKey:["accounts"],queryFn:()=>api.accounts()});
 return <Page eyebrow="Treasury and merchants" title="Accounts" copy="Versioned balance projections backed by immutable ledger postings." action={<button className="primary"><Plus/>Open account</button>}><section className="account-grid">{(query.data??[]).map((a,i)=><article className="account" key={a.id}><header><i className={i<2?"wallet":"merchant"}>{i<2?<Landmark/>:<Building2/>}</i><em><span/> {a.status.toLowerCase()}</em></header><p>{a.type}</p><h2>{a.name}</h2><strong>{money(a.balanceMinor,a.currency)}</strong><footer><span>{a.externalRef}</span><b>v{a.version}</b></footer></article>)}</section><article className="panel account-info"><div><Database/><span><strong>Balance projection model</strong>Balances update inside the same PostgreSQL transaction as postings. The immutable journal remains the source of truth.</span></div><button>Read architecture decision <ArrowUpRight/></button></article></Page>
}
function Ledger(){
 const query=useQuery({queryKey:["ledger"],queryFn:()=>api.ledger()}),accounts=useQuery({queryKey:["accounts"],queryFn:()=>api.accounts()}).data??[],names=Object.fromEntries(accounts.map(a=>[a.id,a.name]));
 return <Page eyebrow="Double-entry journal" title="Ledger" copy="Every movement is immutable, balanced and traceable to its originating payment." action={<button><FileClock/>Export journal</button>}><section className="ledger-summary"><div><ShieldCheck/><span><strong>Journal balanced</strong><small>£1,286,742.00 debits = credits</small></span></div><div><BookOpen/><span><strong>1,842 entries</strong><small>3,684 immutable postings</small></span></div><div><Activity/><span><strong>12 sec ago</strong><small>Latest integrity check</small></span></div></section><section className="entries">{(query.data??[]).map(e=><LedgerRow key={e.id} entry={e} names={names}/>)}</section></Page>
}
function LedgerRow({entry,names}:{entry:LedgerEntry;names:Record<string,string>}){const [expanded,setExpanded]=useState(false);return <article className={expanded?"entry expanded":"entry"}><button onClick={()=>setExpanded(!expanded)}><i><BookOpen/></i><span><b>{entry.description}</b><small>{entry.reference}</small></span><em><Check/> {entry.status.toLowerCase()}</em><strong>{money(entry.postings[0]?.amountMinor??0,entry.postings[0]?.currency)}</strong><time>{date(entry.occurredAt)}</time><ChevronDown/></button>{expanded&&<div>{entry.postings.map((p,i)=><p key={i}><i className={p.direction.toLowerCase()}>{p.direction==="DEBIT"?<ArrowUpRight/>:<ArrowDownLeft/>}</i><span><strong>{names[p.accountId]??short(p.accountId)}</strong><small>{p.accountId}</small></span><b>{p.direction==="DEBIT"?"−":"+"}{money(p.amountMinor,p.currency)}</b></p>)}<footer><ShieldCheck/> Balanced journal entry · immutable after posting</footer></div>}</article>}

const curlExample=[
 "curl --request POST http://localhost:8080/api/v1/payments",
 "  --header 'X-Tenant-Id: northstar'",
 "  --header 'Idempotency-Key: order-88422'",
 "  --header 'Content-Type: application/json'",
 "  --data '{",
 "    \"merchantReference\": \"ORD-88422\",",
 "    \"sourceAccountId\": \"11111111-...\",",
 "    \"destinationAccountId\": \"33333333-...\",",
 "    \"amountMinor\": 125000,",
 "    \"currency\": \"GBP\"",
 "  }'",
].join("\n");
function Developers(){
 const endpoints=[["POST","/api/v1/payments","Create an idempotent account transfer"],["GET","/api/v1/payments","List tenant-scoped payments"],["GET","/api/v1/accounts","Read balance projections"],["GET","/api/v1/ledger/entries","Inspect immutable journal entries"],["GET","/actuator/prometheus","Scrape operational metrics"]];
 return <Page eyebrow="Integration surface" title="Developers" copy="Versioned APIs, explicit contracts and operational tooling for production integrations." action={<button className="primary"><KeyRound/>Create API key</button>}><section className="dev-grid"><article className="panel endpoints"><PanelTitle eyebrow="REST API · v1" title="Endpoints"/>{endpoints.map(([method,path,desc])=><div key={path}><b className={method.toLowerCase()}>{method}</b><code>{path}</code><span>{desc}</span><button><Copy/></button></div>)}</article><article className="panel code"><header><span>cURL</span><button><Copy/> Copy</button></header><pre>{curlExample}</pre><footer><i/><span>201 Created</span><b>84 ms</b></footer></article></section><section className="contract-grid"><article><ShieldCheck/><h3>OAuth2 resource server</h3><p>JWT scopes separate ledger reads from payment writes.</p></article><article><Boxes/><h3>Transactional outbox</h3><p>Committed payments become ordered Kafka lifecycle events.</p></article><article><ServerCog/><h3>Observable by default</h3><p>Health probes, Prometheus metrics and trace correlation.</p></article></section></Page>
}
